services:
  bc-postgres:
    image: postgres:latest
    container_name: bc-postgres
    networks:
      - bc-network
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - default.env
      - .env
    volumes:
      - bc-pg-data:/data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5

  bc-service:
    container_name: bc-service
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    env_file:
      - default.env
      - .env
    depends_on:
      bc-postgres:
        condition: service_healthy
    networks:
      - bc-network

networks:
  bc-network:
    driver: bridge

volumes:
  bc-pg-data: