services:
  bc-postgres:
    image: postgres:latest
    container_name: bc-postgres
    networks:
      - bc-network
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - bc-pg-data:/data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5

  bc-redis:
    image: redis:latest
    container_name: bc-redis
    networks:
      - bc-network
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --appendonly yes

  # bc-service:
  #   container_name: bc-service
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - "${SERVICE_PORT}:${SERVICE_PORT}"
  #   env_file:
  #     - .env
  #   environment:
  #     - POSTGRES_HOST=bc-postgres
  #     - POSTGRES_PORT=5432
  #   depends_on:
  #     bc-postgres:
  #       condition: service_healthy
  #   networks:
  #     - bc-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: bc-pgadmin
    restart: always
    ports:
      - "5433:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - bc-pgadmin-data:/var/lib/pgadmin
    networks:
      - bc-network

networks:
  bc-network:
    driver: bridge

volumes:
  bc-pg-data:
  bc-pgadmin-data: